### ISSUE TITLE
Improve: Improve UI/Ux of the application

### ISSUE THREAD

**Issue by AdityaSingh-02** [AdityaSingh-02/EzEStreamz#18]
The Current Ui is basic, please contribute and improve.

**Comment by Sanyam-jain30** [comment]
Can I please assigne to it? 
If okay, I will share you UI design soon.

**Comment by AdityaSingh-02** [comment]
hey sure I would really appreciate if you would like to contribute. 😊

**Comment by Sanyam-jain30** [comment]
@AdityaSingh-02 due you have any assets to be used in UI design particularly?

**Comment by AdityaSingh-02** [comment]
> @AdityaSingh-02 due you have any assets to be used in UI design particularly?

Hey i have other issues opened with design attached into them you can refer there and if you want i will assign any one of them to you > #21  and #20

**Comment by Sanyam-jain30** [comment]
Yeah sure, I think #20 would be a great issue to work on. Can you please assign it to me?

**Comment by AdityaSingh-02** [comment]
yeah sure you can work on that, hey could you write any message in issue #20  so that I can assign you the issue
