### ISSUE TITLE
style: update login page

### ISSUE THREAD

**Issue by AdityaSingh-02** [AdityaSingh-02/EzEStreamz#20]
**Description**
The Current login page does not have a properly designed login page.
we would really appreciate if someone could contribute and replace the current login page with the image attached below.

**Requirements**
- Tailwindcss/CSS
- ReactJs

- [x] There is no drop in test coverage.

<img width="824" alt="Screenshot 2023-09-30 at 10 47 22 PM" src="https://github.com/AdityaSingh-02/EzEStreamz/assets/94185167/f77ef9a0-6643-40e1-863e-57c4d5afc554">

**Comment by Sanyam-jain30** [comment]
Can you please assign it to me?
